### ISSUE TITLE
你好，请问PeMS.h5这个文件在哪啊？

### ISSUE THREAD

**Issue by Qofsd** [zhengchuanpan/GMAN#14]
运行时报错：
File data/PeMS.h5 does not exist

**Comment by Qofsd** [comment]
啊，我找到了。。。不过训练要好久啊，我拿实验室服务器跑了半天

**Comment by childe-wuhen** [comment]
请问在哪里呀

**Comment by h30306** [comment]
想請教在哪裡找得到PeMS.h5?

**Comment by YUAN97Q** [comment]
@Qofsd 您好，我想请教一下 作者原始的这个代码是如何跑通的？我在utils的73，74行 timeofday = (Time.hour * 3600 + Time.minute * 60 + Time.second) // Time.freq.delta.total_seconds() 这部分会报错 跪求大佬指点😭

**Comment by YUAN97Q** [comment]
@h30306 @childe-wuhen 在作者README.md 的Data部分有分享数据
