### ISSUE TITLE
numpy版本

### ISSUE THREAD

**Issue by LMissher** [zhengchuanpan/GMAN#17]
numpy 1.18.4 pypi_0 pypi

**Comment by LiFXe** [comment]
您好，想请问下您用的numpy版本，谢谢您

**Comment by LMissher** [comment]
numpy                     1.18.4                   pypi_0    pypi
您好这是我使用的numpy版本。

**Comment by LiFXe** [comment]
烦请再问下您使用的tensorflow版本，谢谢您
