### ISSUE TITLE
AttributeError: 'numpy.bytes_' object has no attribute 'delta'

### ISSUE THREAD

**Issue by LiFXe** [zhengchuanpan/GMAN#18]
GMAN-master/PeMS/utils.py", line 74, in loadData
    // Time.freq.delta.total_seconds()
AttributeError: 'numpy.bytes_' object has no attribute 'delta'

作者您好，请问如何解决呢，我的环境：tf-1.14-py3

**Comment by GuYingwife** [comment]
你们解决了嘛 我也遇到这个报错了 环境tf-2.3.1 py-3

**Comment by TBS1234** [comment]
请问您解决了吗？我也有同样的问题

**Comment by flowingrain** [comment]
分母采用(5*60)，时间片的长度

**Comment by garff** [comment]
分母采用(5*60)，时间片的长度 = The denominator is (5*60), the length of the time slice

**Comment by garff** [comment]
> 分母采用(5*60)，时间片的长度

分母采用(560)，时间片的长度 = The denominator is (560), the length of the time slice

And thanks!

**Comment by tarekbzahid** [comment]
having the same error, do you have the solution? Thanks!

**Comment by mad-stat** [comment]
Could anyone solve this?
